export const marketplaceCategories = [
  'Free Stuff',
  'Electronics',
  'Power Tools & DIY',
  'Gardening',
  'Furniture',
  'Books',
  'Tools',
  'Cars',
  'Car Parts',
  'Bikes & E-bikes',
  'Phones',
  'Computers',
  'TVs & Audio',
  'Gaming',
  'Home & Kitchen',
  'Appliances',
  'Baby & Kids',
  'Toys',
  'Clothing',
  'Shoes & Accessories',
  'Beauty',
  'Sports & Outdoors',
  'Music & Instruments',
  'Art & Crafts',
  'Office',
  'Pet Supplies',
  'Storage',
  'Business Equipment',
  'Services',
];
